name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, whispervote-signature]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: rebuild docker image
        run: sudo docker compose build whispervote-frontend --no-cache

      - name: Run docker compose
        run: sudo docker compose up -d
